var i = 0;
function addQuestion(){
    var down_content = document.getElementsByClassName('down_content')[0];
    var code="";
    code +="\<div class='down_content_question'>";
    code +="\<div class='down_content_question_up'>";
    code +="\<div class='down_content_question_up_img'>";
    code +="\</div>";
    code +="\<div style='float:right;margin-top: 10px;margin-right: 45%'>";
    code +="\<a>";
    code +="问题类型：";
    code +="\</a>";
    code +="<select class='dOm' style='width: 100px;height:30px;'";
    code +=">";
    code +="\<option>";
    code +="单选";
    code +="\</option>";
    code +="\<option>";
    code +="多选";
    code +="\</option>";
    code +="\</select>&nbsp&nbsp&nbsp";
    code +="\<a>";
    code +="题干：";
    code +="\</a>";
    code +="<input type='text' ";
    code +="style='width:272px;height:30px;'";
    code +=">"
    code +="\</div>";
    code +="\</div>";
    code +="<div class='down_content_question_down'";
    code +=">";
    code +="<div id='input"+i+"' style='width:97%;float:left;' ";
    code +=">";
    code +="<span style='margin-left: 32px;'";
    code +=">";
    code +="答案";
    code +="\</span>";
    code +="\<span>";
    code +="\<a>";
    code +="A: ";
    code +="\</a>";
    code +="\<input type='text' >";
    code +="\</span>";
    code +="\<span>";
    code +="\<a>B: </a>";
    code +="\<input type='text'>";
    code +="\</span>";
    code +="\<span>";
    code +="\<a>C: </a>";
    code +="\<input type='text'>";
    code +="\</span>";
    code +="\<span id='br"+i+"'>";
    code +="\<a>D: </a>";
    code +="\<input id ='last"+i+"' type='text' onblur='addOneOption("+i+")'>";
    //code +="\<input id ='last"+i+"' type='text' onblur='alert(123)'>";
    code +=" \</span>";
    code +=" \</div>";
    code +=" \</div>";
    code +="\</div>";
    $( down_content).append(code);
    i++;
}

